apiVersion: v1
kind: Service
metadata:
  name: pingpong-db-svc
  namespace: experimental
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: ping-pong-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ping-pong-db
  namespace: experimental
spec:
  serviceName: ping-pong-db
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-db
  template:
    metadata:
      labels:
        app: ping-pong-db
    spec:
      containers:
      - name: ping-pong-db
        image: viktormandlbauer/ping-pong-db:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: ping-pong-config
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ping-pong-secrets
              key: DB_PASSWORD
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: experimental
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-data-log-output
          persistentVolumeClaim:
            claimName: pvc1
      containers:
        - name: ping-pong
          image: viktormandlbauer/ping-pong:latest
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: ping-pong-config
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: ping-pong-config
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ping-pong-secrets
                key: DB_PASSWORD
          volumeMounts:
            - name: shared-data-log-output
              mountPath: /usr/src/app/files
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: experimental
  name: ping-pong-svc
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - port: 2348
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ping-pong-config
  namespace: experimental
data:
  DB_HOST: ping-pong-svc.experimental
  DB_USER: pingpong