apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
  namespace: experimental
spec:
  storageClassName: pv2-agents-filesystem
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/experimental
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0
          - k3d-k3s-default-agent-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: experimental
spec:
  storageClassName: pv2-agents-filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---