apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-todo
  template:
    metadata:
      labels:
        app: app-todo
    spec:
      containers:
      - name: app-todo
        image: viktormandlbauer/todo-app:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
      - name: postgres-todo
        image: viktormandlbauer/postgres-db-todo:latest
        env:
        - name: POSTGRES_DB
          value: todo
        - name: POSTGRES_USER
          value: todo
        - name: POSTGRES_PASSWORD
          value: todo
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: app-todo-svc
spec:
  type: ClusterIP
  selector:
    app: app-todo
  ports:
    - name: app-todo
      port: 2349
      protocol: TCP
      targetPort: 3000
---