# Cluster IP Service for simple-html
apiVersion: v1
kind: Service
metadata:
  name: simple-html-svc
spec:
  type: ClusterIP
  selector:
    app: simple-html
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
---

# Cluster IP Service for log-output
apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - name: log-output-reader
      port: 2346
      protocol: TCP
      targetPort: 3000
    - name: log-output-writer
      port: 2347
      protocol: TCP
      targetPort: 3001
---

# Cluster IP Service for ping-pong
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - port: 2348
      protocol: TCP
      targetPort: 3000
---

# Service with NodePort
#apiVersion: v1
#kind: Service
#metadata:
#  name: simple-html-svc
#spec:
#  type: NodePort
#  selector:
#    app: simple-html
#  ports:
#    - name: http
#      protocol: TCP
#      port: 3000
#      targetPort: 3000
#      nodePort: 30000