apiVersion: v1
kind: Service
metadata:
  name: uuid-generator-service
spec:
  selector:
    app: uuid-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
